version: "3"

services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: onix
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: world-tour
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build: .
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/world-tour
      SPRING_DATASOURCE_USERNAME: onix
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"

volumes:
  postgres-data: