version: "3"

services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: wxamsxipwlutke
      POSTGRES_PASSWORD: 7256fb6fa43e5a50b7c01b302e95d0831482c83b17f08536895375850037f72c
      POSTGRES_DB: df5u53e95vjm17
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build: .
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ec2-44-213-151-75.compute-1.amazonaws.com:5432/df5u53e95vjm17
      SPRING_DATASOURCE_USERNAME: wxamsxipwlutke
      SPRING_DATASOURCE_PASSWORD: 7256fb6fa43e5a50b7c01b302e95d0831482c83b17f08536895375850037f72c
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"

volumes:
  postgres-data: